@startuml modelo
hide methods
hide members



Usuario			<-l->		PrefixoLoc
Localizacao		-u->		PrefixoLoc
Localizacao		-r->		Loja
Localizacao		<-u->		Produto
Usuario			-r->		Loja

ItemNota		-d->		Usuario
ItemNota		-d->		(Localizacao, Produto)

ItemNota		-u->		Nota
Nota			-d->		Loja
ItemNota		-u->		Etiqueta
@enduml