@startuml modelo
hide methods

class Produto{
	codigo
	grade
	codebar
	data_cadastro
	tamanho_lote
}

class ItemNota{
	data
	hora
	quantidade
	tamanhoLote
}

class Nota {
	numero
	tipoMov [ENTRADA, SAIDA]
	data
	hora
	observacao
}

class Lote {
	sequencia
	total
	saldo
}

class Movimentacao {
	quantidade
}

class Loja {
	numero
}

class Usuario {
	numero
}

class Label {
	tipo [NORMAL, PECA, BOBINA, CAIXA]
	layoutEntrada
	layoutSaida
}


ItemNota	-u->	Nota
ItemNota	-->	Produto
Lote		-->	Produto
Lote		-u->	Loja
Movimentacao	-l->	Lote
Movimentacao	-r->	ItemNota
Nota		-l->	Loja
Usuario		-r->	Loja
Produto		-l->	Label
@enduml
