@startuml
class Produto{
	codigo
	data_cadastro
}

class ItemEntrada{
	quantidade
	custo
}

class NotaEntrada{
	numero
	loja
	data
	hora
}

class ItemSaida{
	quantidade
	custo
}

class NotaSaida{
	loja
	data
	hora
}

class Saldo{
	loja
	quantidade
}

NotaEntrada	<-- ItemEntrada
NotaSaida	<-- ItemSaida
ItemEntrada	-->	Produto
ItemSaida	-->	Produto
Saldo		-u->	Produto
@enduml
