@startuml modelo
class Produto{
	codigo
	data_cadastro
}

class ItemEntrada{
	quantidade
	custo_unitario
}

class Entrada{
	numero
	loja
	data
	hora
}

class ItemSaida{
	quantidade
	custo_unitario
}

class Saida{
	loja
	data
	hora
}

class Saldo{
	loja
	quantidade
}

Entrada	<-- ItemEntrada
Saida	<-- ItemSaida
ItemEntrada	-->	Produto
ItemSaida	-->	Produto
Saldo		-->	Produto
@enduml
