@startuml modelo
hide methods

class Produto{
	codigo
	grade
	codebar
	data_cadastro
	tipo [NORMAL, PECA, BOBINA, CAIXA]
	quant_lote
	quant_bobina
}

class ItemNota{
	quantidade
}

class Nota {
	numero
	tipoMov [ENTRADA, SAIDA]
	data
	hora
	observacao
}

class Lote {
	sequencia
	total
}

class Movimentacao {
	quantidade
	saldo
}

class Loja {
	numero
}

class Usuario {
	numero
}

class Saldo {
	quantidade
}

ItemNota	-r->	Nota
ItemNota	-l->	Produto
Lote		-->	Produto
Movimentacao	-l->	Lote
Movimentacao	-->	ItemNota
Nota		-->	Loja
Usuario		-l->	Loja
Saldo		-u->	Produto
Saldo		-r->	Loja
@enduml
